### ISSUE TITLE
Desarrollo de script que integre las actividades del análisis anterior

### ISSUE THREAD

**Issue by iduranm** [dgb-sistemas/biblat_process#1]
**Criterios de aceptación**
- Script de python que ejecute las intrucciones del print_03 e importe los datos

**Duración**
- 6 días

**Restricciones**
- Se debe completar 4 tareas anteriores (#5 #6 #7 #8)

**Comment by arturorc** [comment]
Les comparto el script actual con el que realizo el dump de las bases.
https://gist.github.com/arturorc/d9169b7ddfa66fc24a689b55836b18c5
