### ISSUE TITLE
Proceso para generar el listado de números de sistema para el comando print_03

### ISSUE THREAD

**Issue by iselagb27** [dgb-sistemas/biblat_process#5]
## Criterios de aceptación
Instrucciones para generar el listado
## Duración
1.5 horas

**Comment by iselagb27** [comment]
## Instrucciones para generar listado de números de sistema (p_ret_01) necesario para generar el print_03

Las bases de Clase y Periódica se alojan en el servidor 132.248.9.1 y la conexión tanto desde SSH como en el GUI son con el usuario "aleph"

## 1. Instrucción desde línea de comando: 
```
dlib base01
cd /exlibris/aleph/a21_1/aleph/proc
csh -f p_ret_01 BASE01,,archivo_salida,000000000,999999999,,00,00000000,99999999,00000000,99999999,,AND,NOT,,,,,,,,,,,,,,,,,,,,,,00000000,99999999,ALEPH,01,
```
El archivo de salida se guarda en el directorio $alephe_scratch (/exlibris/aleph/u21_1/alephe/scratch)

Tiempo aproximado: 15 min.
(Incluye los registros marcados como DEL en la base)

## 2. Instrucción desde una consulta SQLPLUS:
```sql
SET HEADING ON
SET LINESIZE 14 
SET ECHO OFF                                                                    
SET FEEDBACK OFF                                                                
SET PAUSE OFF                                                                   
SET NEWPAGE 0                                                                   
SET SPACE 0                                                                     
SET PAGESIZE 0                                                                  
SET TERMOUT OFF                                                                 
SET VERIFY OFF                                                                  
                                                              
SPOOL /exlibris/aleph/a21_1/alephm/sql_report/anexo/biblat_process/archivo_salida

select substr(z13u_rec_key,1,9)||'BASE01'
from BASE01.z13u
where z13u_user_defined_3_code is NULL
order by substr(z13u_rec_key,1,9);

SPOOL OFF

EXIT
```
 **Ejecución del archivo con SQLPLUS**  
```
sqlplus base01/base01 @consulta.sql
```
Tiempo aproximado: 2 min.
(Excluye los registros marcados como DEL en la base)

**Comment by EJAJDGB** [comment]
Para redireccionar la impresion de los resultados de las consultas en sqlplus:

``
SPOOL </ruta_del_archivo/nombre_del_archivo>
``

Se utiliza antes de ejecutar las consultas.

Nota: lo agrego aqui, ya que no puedo editar el comentario anterior de @iselagb27

**Comment by iselagb27** [comment]
Ok gracias Efraín
